//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Account
{
    public int UserId { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string UserAccess { get; set; }
    public byte AdminStatus { get; set; }
}

public partial class Audit_Log
{
    public int Id { get; set; }
    public string ItemId { get; set; }
    public string UserId { get; set; }
    public string Date { get; set; }
    public string Time { get; set; }
    public string Page { get; set; }
    public string Page_Action { get; set; }
    public string Name { get; set; }
}

public partial class Breakfast_Price_Tier
{
    public int Id { get; set; }
    public string Price_Tier { get; set; }
}

public partial class BUSINESS_EXT
{
    public int ID { get; set; }
    public string LONGNM { get; set; }
}

public partial class CSHMIMP0
{
    public int MIMMIC { get; set; }
    public string MIMSTA { get; set; }
    public string MIMFGC { get; set; }
    public string MIMNAM { get; set; }
    public string MIMDSC { get; set; }
    public string MIMSSC { get; set; }
    public string MIMDPC { get; set; }
    public string MIMCIN { get; set; }
    public Nullable<int> MIMDGC { get; set; }
    public string MIMASC { get; set; }
    public string MIMTXC { get; set; }
    public Nullable<int> MIMUTC { get; set; }
    public string MIMDWE { get; set; }
    public string MIMTCI { get; set; }
    public Nullable<double> MIMPRI { get; set; }
    public string MIMTCA { get; set; }
    public Nullable<double> MIMPRO { get; set; }
    public string MIMTCG { get; set; }
    public Nullable<double> MIMPRG { get; set; }
    public Nullable<System.DateTime> MIMPND { get; set; }
    public Nullable<int> MIMKBP { get; set; }
    public string MIMKSC { get; set; }
    public string MIMSKT { get; set; }
    public string MIMGRP { get; set; }
    public string MIMWLV { get; set; }
    public string MIMWSD { get; set; }
    public string MIMWGR { get; set; }
    public string MIMHPT { get; set; }
    public string MIMUSR { get; set; }
    public Nullable<System.DateTime> MIMDAT { get; set; }
    public Nullable<System.DateTime> MIMEDT { get; set; }
    public Nullable<bool> MIMFLG { get; set; }
    public string MIMBIN { get; set; }
    public Nullable<int> MIMBIT { get; set; }
    public string MIMBIR { get; set; }
    public string MIMBGR { get; set; }
    public Nullable<int> MIMBQU { get; set; }
    public string MIMGRA { get; set; }
    public string MIMIST { get; set; }
    public string MIMCLR { get; set; }
    public Nullable<double> MIMNPI { get; set; }
    public Nullable<double> MIMNPO { get; set; }
    public Nullable<double> MIMNPD { get; set; }
    public Nullable<int> MIMSKI { get; set; }
    public Nullable<int> MIMBMI { get; set; }
    public Nullable<double> MIMNPA { get; set; }
    public Nullable<double> MIMNNP { get; set; }
    public string MIMNPT { get; set; }
    public Nullable<int> MIMMIC_NP6 { get; set; }
    public string MIMLON { get; set; }
    public string STATUS { get; set; }

    public virtual CSHMIMP0_NP6 CSHMIMP0_NP6 { get; set; }
}

public partial class CSHMIMP0_NP6
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CSHMIMP0_NP6()
    {
        this.CSHMIMP0 = new HashSet<CSHMIMP0>();
    }

    public int MIMMIC { get; set; }
    public string MIMSTA { get; set; }
    public string MIMNAM { get; set; }
    public string MIMLON { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CSHMIMP0> CSHMIMP0 { get; set; }
}

public partial class CSHVMLP0
{
    public int VMLNUM { get; set; }
    public Nullable<int> VMLMIC { get; set; }
    public Nullable<int> VMLQUA { get; set; }
    public string VMLNAM { get; set; }
    public Nullable<double> VMLPRI { get; set; }
    public Nullable<double> VMLPRO { get; set; }
    public string VMLID { get; set; }
    public string STATUS { get; set; }
}

public partial class CSM_Master_Recipe
{
    public string CSMID { get; set; }
    public Nullable<int> RIMRIC { get; set; }
    public Nullable<double> CSMSFQ { get; set; }
    public string CSMCWC { get; set; }
    public string CSMDES { get; set; }
}

public partial class Dessert_Price_Tier
{
    public int Id { get; set; }
    public string Price_Tier { get; set; }
}

public partial class INVRIMP0
{
    public int RIMRIC { get; set; }
    public Nullable<int> RIMVPC { get; set; }
    public string RIMRID { get; set; }
    public string RIMRIG { get; set; }
    public string RIMTEM { get; set; }
    public string RIMPGR { get; set; }
    public string RIMPIS { get; set; }
    public string RIMBVP { get; set; }
    public string RIMBZP { get; set; }
    public string RIMUMC { get; set; }
    public Nullable<double> RIMUPC { get; set; }
    public Nullable<double> RIMSUQ { get; set; }
    public Nullable<int> RIMLAY { get; set; }
    public Nullable<double> RIMCPR { get; set; }
    public Nullable<double> RIMCPN { get; set; }
    public Nullable<System.DateTime> RIMPDT { get; set; }
    public Nullable<int> RIMPVN { get; set; }
    public Nullable<int> RIMSVN { get; set; }
    public string RIMCWC { get; set; }
    public string RIMPRO { get; set; }
    public string RIMSE4 { get; set; }
    public string RIMERT { get; set; }
    public Nullable<double> RIMUSF { get; set; }
    public Nullable<double> RIMSDP { get; set; }
    public Nullable<double> RIMUS1 { get; set; }
    public Nullable<double> RIMUS2 { get; set; }
    public Nullable<double> RIMUS3 { get; set; }
    public Nullable<double> RIMUS4 { get; set; }
    public Nullable<double> RIMUS5 { get; set; }
    public Nullable<double> RIMUSX { get; set; }
    public Nullable<double> RIMMSD { get; set; }
    public Nullable<double> RIMMSL { get; set; }
    public string RIMLA1 { get; set; }
    public string RIMLA2 { get; set; }
    public Nullable<int> RIMLP1 { get; set; }
    public Nullable<int> RIMLP2 { get; set; }
    public string RIMSTA { get; set; }
    public string RIMUSR { get; set; }
    public Nullable<System.DateTime> RIMDAT { get; set; }
    public Nullable<System.DateTime> RIMEDT { get; set; }
    public Nullable<bool> RIMFLG { get; set; }
    public string RIMORD { get; set; }
    public Nullable<int> RIMLIN { get; set; }
    public string RIMADE { get; set; }
    public string RIMBAR { get; set; }
    public string STATUS { get; set; }
    public string Store { get; set; }
    public string Except_Store { get; set; }
    public string Location { get; set; }
    public string Store_Attrib { get; set; }
}

public partial class INVRIRP0
{
    public string RIRRID { get; set; }
    public Nullable<int> RIRMIC { get; set; }
    public Nullable<int> RIRRIC { get; set; }
    public Nullable<int> RIRVPC { get; set; }
    public Nullable<double> RIRSFQ { get; set; }
    public string RIRCWC { get; set; }
    public string RIRSTA { get; set; }
    public string RIRVST { get; set; }
    public string RIRUSR { get; set; }
    public Nullable<System.DateTime> RIRDAT { get; set; }
    public Nullable<bool> RIRFLG { get; set; }
    public string STATUS { get; set; }
    public Nullable<double> RIMCPR { get; set; }
    public string LongName { get; set; }
    public string Description { get; set; }
}

public partial class INVVEMP0
{
    public int VEMVEN { get; set; }
    public Nullable<int> VEMWSI { get; set; }
    public string VEMDS1 { get; set; }
    public string VEMDS2 { get; set; }
    public string VEMCCD { get; set; }
    public string VEMZIP { get; set; }
    public string VEMCTY { get; set; }
    public string VEMSTR { get; set; }
    public string VEMTEL { get; set; }
    public string VEMSTN { get; set; }
    public string VEMLOC { get; set; }
    public Nullable<double> VEMDAY { get; set; }
    public string VEMTID { get; set; }
    public string VEMSTA { get; set; }
    public Nullable<System.DateTime> VEMDAT { get; set; }
    public string VEMUSR { get; set; }
    public string VEMADE { get; set; }
    public string VEMDEL { get; set; }
    public string STATUS { get; set; }
}

public partial class LOCATION
{
    public int Id { get; set; }
    public string LOCATN { get; set; }
}

public partial class McCafe_Bistro_Price_Tier
{
    public int Id { get; set; }
    public string Price_Tier { get; set; }
}

public partial class McCafe_Level_2_Price_Tier
{
    public int Id { get; set; }
    public string Price_Tier { get; set; }
}

public partial class McCafe_Level_3_Price_Tier
{
    public int Id { get; set; }
    public string Price_Tier { get; set; }
}

public partial class MDS_Price_Tier
{
    public int Id { get; set; }
    public string Price_Tier { get; set; }
}

public partial class OWNERSHIP
{
    public int Id { get; set; }
    public string OWNSHP { get; set; }
}

public partial class PROFIT_CEN
{
    public int Id { get; set; }
    public string PRFCNT { get; set; }
}

public partial class Project_Gold_Price_Tier
{
    public int Id { get; set; }
    public string Price_Tier { get; set; }
}

public partial class Regular_Price_Tier
{
    public int Id { get; set; }
    public string Price_Tier { get; set; }
}

public partial class RIM_VEM_Lookup
{
    public string RIM_VEM_ID { get; set; }
    public Nullable<int> RIMRIC { get; set; }
    public string RIMRID { get; set; }
    public Nullable<int> VEMVEN { get; set; }
    public string VEMDS1 { get; set; }
    public Nullable<double> RIMCPR { get; set; }
    public Nullable<double> PPERUN { get; set; }
    public Nullable<double> SCMCOD { get; set; }
    public Nullable<double> RIMCPN { get; set; }
    public Nullable<System.DateTime> RIMPDT { get; set; }
}

public partial class SCM_Master_Recipe
{
    public string CSMID { get; set; }
    public Nullable<int> RIMRIC { get; set; }
    public Nullable<double> CSMSFQ { get; set; }
    public string CSMCWC { get; set; }
    public string CSMDES { get; set; }
}

public partial class STORE_MIMMIC_Lookup
{
    public string STORE_MIMMIC_Id { get; set; }
    public Nullable<int> STORE_NO { get; set; }
    public Nullable<int> MIMMIC { get; set; }
}

public partial class Store_Profile
{
    public int STORE_NO { get; set; }
    public string STORE_NAME { get; set; }
    public string OWNERSHIP { get; set; }
    public string BREAKFAST_PRICE_TIER { get; set; }
    public string REGULAR_PRICE_TIER { get; set; }
    public string DC_PRICE_TIER { get; set; }
    public string MDS_PRICE_TIER { get; set; }
    public string MCCAFE_LEVEL_2_PRICE_TIER { get; set; }
    public string MCCAFE_LEVEL_3_PRICE_TIER { get; set; }
    public string MCCAFE_BISTRO_PRICE_TIER { get; set; }
    public string PROJECT_GOLD_PRICE_TIER { get; set; }
    public string BET { get; set; }
    public Nullable<int> PROFIT_CENTER { get; set; }
    public string REGION { get; set; }
    public string PROVINCE { get; set; }
    public string LOCATION { get; set; }
    public string ADDRESS { get; set; }
    public string CITY { get; set; }
    public string FRESH_OR_FROZEN { get; set; }
    public string PAPER_OR_PLASTIC { get; set; }
    public string SOFT_SERVE_OR_VANILLA_POWDER_MIX { get; set; }
    public string SIMPLOT_OR_MCCAIN { get; set; }
    public string MCCORMICK_OR_GSF { get; set; }
    public string STATUS { get; set; }
}

public partial class Tier_Lookup
{
    public int MIMMIC { get; set; }
    public Nullable<double> OLDPRA { get; set; }
    public Nullable<double> NEWPRA { get; set; }
    public Nullable<double> OLDPAO { get; set; }
    public Nullable<double> NEWPAO { get; set; }
    public Nullable<double> OLDAOT { get; set; }
    public Nullable<double> NEWAOT { get; set; }
    public Nullable<double> OLDNPA { get; set; }
    public Nullable<double> NEWNPA { get; set; }
    public Nullable<double> OLDPRB { get; set; }
    public Nullable<double> NEWPRB { get; set; }
    public Nullable<double> OLDPBO { get; set; }
    public Nullable<double> NEWPBO { get; set; }
    public Nullable<double> OLDBOT { get; set; }
    public Nullable<double> NEWBOT { get; set; }
    public Nullable<double> OLDNPB { get; set; }
    public Nullable<double> NEWNPB { get; set; }
    public Nullable<double> OLDPRC { get; set; }
    public Nullable<double> NEWPRC { get; set; }
    public Nullable<double> OLDPCO { get; set; }
    public Nullable<double> NEWPCO { get; set; }
    public Nullable<double> OLDCOT { get; set; }
    public Nullable<double> NEWCOT { get; set; }
    public Nullable<double> OLDNPC { get; set; }
    public Nullable<double> NEWNPC { get; set; }
    public Nullable<double> OLDPRD { get; set; }
    public Nullable<double> NEWPRD { get; set; }
    public Nullable<double> OLDPDO { get; set; }
    public Nullable<double> NEWPDO { get; set; }
    public Nullable<double> OLDDOT { get; set; }
    public Nullable<double> NEWDOT { get; set; }
    public Nullable<double> OLDNPD { get; set; }
    public Nullable<double> NEWNPD { get; set; }
    public Nullable<double> OLDPRE { get; set; }
    public Nullable<double> NEWPRE { get; set; }
    public Nullable<double> OLDPEO { get; set; }
    public Nullable<double> NEWPEO { get; set; }
    public Nullable<double> OLDEOT { get; set; }
    public Nullable<double> NEWEOT { get; set; }
    public Nullable<double> OLDNPE { get; set; }
    public Nullable<double> NEWNPE { get; set; }
    public Nullable<double> OLDPRF { get; set; }
    public Nullable<double> NEWPRF { get; set; }
    public Nullable<double> OLDPFO { get; set; }
    public Nullable<double> NEWPFO { get; set; }
    public Nullable<double> OLDFOT { get; set; }
    public Nullable<double> NEWFOT { get; set; }
    public Nullable<double> OLDNPF { get; set; }
    public Nullable<double> NEWNPF { get; set; }
    public Nullable<double> OLDMDS { get; set; }
    public Nullable<double> NEWMDS { get; set; }
    public Nullable<double> OLDMDO { get; set; }
    public Nullable<double> NEWMDO { get; set; }
    public Nullable<double> OLDMOT { get; set; }
    public Nullable<double> NEWMOT { get; set; }
    public Nullable<double> OLDMDN { get; set; }
    public Nullable<double> NEWMDN { get; set; }
    public Nullable<double> OLDPRS { get; set; }
    public Nullable<double> NEWPRS { get; set; }
    public Nullable<double> OLDPSO { get; set; }
    public Nullable<double> NEWPSO { get; set; }
    public Nullable<double> OLDSOT { get; set; }
    public Nullable<double> NEWSOT { get; set; }
    public Nullable<double> OLDNPS { get; set; }
    public Nullable<double> NEWNPS { get; set; }
    public Nullable<System.DateTime> EDTA { get; set; }
    public Nullable<System.DateTime> PNDA { get; set; }
    public Nullable<System.DateTime> EDTB { get; set; }
    public Nullable<System.DateTime> PNDB { get; set; }
    public Nullable<System.DateTime> EDTC { get; set; }
    public Nullable<System.DateTime> PNDC { get; set; }
    public Nullable<System.DateTime> EDTD { get; set; }
    public Nullable<System.DateTime> PNDD { get; set; }
    public Nullable<System.DateTime> EDTE { get; set; }
    public Nullable<System.DateTime> PNDE { get; set; }
    public Nullable<System.DateTime> EDTF { get; set; }
    public Nullable<System.DateTime> PNDF { get; set; }
    public Nullable<System.DateTime> EDTM { get; set; }
    public Nullable<System.DateTime> PNDM { get; set; }
    public Nullable<System.DateTime> EDTS { get; set; }
    public Nullable<System.DateTime> PNDS { get; set; }
}
