//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSHMIMP0
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSHMIMP0()
        {
            this.INVRIRP0 = new HashSet<INVRIRP0>();
            this.MIM_Price = new HashSet<MIM_Price>();
        }
    
        public int MIMMIC { get; set; }
        public string MIMSTA { get; set; }
        public string MIMFGC { get; set; }
        public string MIMNAM { get; set; }
        public string MIMDSC { get; set; }
        public string MIMSSC { get; set; }
        public string MIMDPC { get; set; }
        public string MIMCIN { get; set; }
        public Nullable<int> MIMDGC { get; set; }
        public string MIMASC { get; set; }
        public string MIMTXC { get; set; }
        public Nullable<int> MIMUTC { get; set; }
        public string MIMDWE { get; set; }
        public string MIMTCI { get; set; }
        public Nullable<double> MIMPRI { get; set; }
        public string MIMTCA { get; set; }
        public Nullable<double> MIMPRO { get; set; }
        public string MIMTCG { get; set; }
        public Nullable<double> MIMPRG { get; set; }
        public Nullable<System.DateTime> MIMPND { get; set; }
        public Nullable<int> MIMKBP { get; set; }
        public string MIMKSC { get; set; }
        public string MIMSKT { get; set; }
        public string MIMGRP { get; set; }
        public string MIMWLV { get; set; }
        public string MIMWSD { get; set; }
        public string MIMWGR { get; set; }
        public string MIMHPT { get; set; }
        public string MIMUSR { get; set; }
        public Nullable<System.DateTime> MIMDAT { get; set; }
        public Nullable<System.DateTime> MIMEDT { get; set; }
        public Nullable<bool> MIMFLG { get; set; }
        public string MIMBIN { get; set; }
        public Nullable<int> MIMBIT { get; set; }
        public string MIMBIR { get; set; }
        public string MIMBGR { get; set; }
        public Nullable<int> MIMBQU { get; set; }
        public string MIMGRA { get; set; }
        public string MIMIST { get; set; }
        public string MIMCLR { get; set; }
        public Nullable<double> MIMNPI { get; set; }
        public Nullable<double> MIMNPO { get; set; }
        public Nullable<double> MIMNPD { get; set; }
        public Nullable<int> MIMSKI { get; set; }
        public Nullable<int> MIMBMI { get; set; }
        public Nullable<double> MIMNPA { get; set; }
        public Nullable<double> MIMNNP { get; set; }
        public string MIMNPT { get; set; }
        public Nullable<int> MIMMIC_NP6 { get; set; }
        public string MIMLON { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Trading_Area { get; set; }
        public Nullable<int> Location { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Store { get; set; }
        public string Except_Store { get; set; }
        public Nullable<int> Group { get; set; }
    
        public virtual CSHMIMP0_NP6 CSHMIMP0_NP6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVRIRP0> INVRIRP0 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MIM_Price> MIM_Price { get; set; }
    }
}
