//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSHPMGP0
    {
        public string PMGGID { get; set; }
        public string PMGGRP { get; set; }
        public string PMGNUM { get; set; }
        public string PMGTXT { get; set; }
        public string PMGSTA { get; set; }
    }
}
