//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSHVMLP0
    {
        public int VMLNUM { get; set; }
        public Nullable<int> VMLMIC { get; set; }
        public Nullable<int> VMLQUA { get; set; }
        public string VMLNAM { get; set; }
        public Nullable<double> VMLPRI { get; set; }
        public Nullable<double> VMLPRO { get; set; }
        public string VMLID { get; set; }
        public string STATUS { get; set; }
    }
}
