//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSM_Master_Recipe
    {
        public string CSMID { get; set; }
        public Nullable<int> RIMRIC { get; set; }
        public Nullable<double> CSMSFQ { get; set; }
        public string CSMCWC { get; set; }
        public string CSMDES { get; set; }
    }
}
