//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVMGRP0
    {
        public string MGRGRP { get; set; }
        public string MGRTXT { get; set; }
        public string MGRSTA { get; set; }
        public string STATUS { get; set; }
    }
}
