//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVRIRP0
    {
        public int RIRRID { get; set; }
        public Nullable<int> RIRMIC { get; set; }
        public Nullable<int> RIRRIC { get; set; }
        public Nullable<int> RIRVPC { get; set; }
        public Nullable<int> RIRSFQ { get; set; }
        public string RIRCWC { get; set; }
        public string RIRSTA { get; set; }
        public string RIRVST { get; set; }
        public string RIRUSR { get; set; }
        public Nullable<System.DateTime> RIRDAT { get; set; }
        public Nullable<bool> RIRFLG { get; set; }
        public string STATUS { get; set; }
    }
}
