//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVRIMP0
    {
        public int RIMRIC { get; set; }
        public Nullable<int> RIMVPC { get; set; }
        public string RIMRID { get; set; }
        public string RIMRIG { get; set; }
        public string RIMTEM { get; set; }
        public string RIMPGR { get; set; }
        public string RIMPIS { get; set; }
        public string RIMBVP { get; set; }
        public string RIMBZP { get; set; }
        public string RIMUMC { get; set; }
        public Nullable<int> RIMUPC { get; set; }
        public Nullable<int> RIMSUQ { get; set; }
        public Nullable<int> RIMLAY { get; set; }
        public Nullable<int> RIMCPR { get; set; }
        public Nullable<int> RIMCPN { get; set; }
        public Nullable<System.DateTime> RIMPDT { get; set; }
        public Nullable<int> RIMPVN { get; set; }
        public Nullable<int> RIMSVN { get; set; }
        public string RIMCWC { get; set; }
        public string RIMPRO { get; set; }
        public string RIMSE4 { get; set; }
        public string RIMERT { get; set; }
        public Nullable<int> RIMUSF { get; set; }
        public Nullable<int> RIMSDP { get; set; }
        public Nullable<int> RIMUS1 { get; set; }
        public Nullable<int> RIMUS2 { get; set; }
        public Nullable<int> RIMUS3 { get; set; }
        public Nullable<int> RIMUS4 { get; set; }
        public Nullable<int> RIMUS5 { get; set; }
        public Nullable<double> RIMUSX { get; set; }
        public Nullable<int> RIMMSD { get; set; }
        public Nullable<int> RIMMSL { get; set; }
        public string RIMLA1 { get; set; }
        public string RIMLA2 { get; set; }
        public Nullable<int> RIMLP1 { get; set; }
        public Nullable<int> RIMLP2 { get; set; }
        public string RIMSTA { get; set; }
        public string RIMUSR { get; set; }
        public Nullable<System.DateTime> RIMDAT { get; set; }
        public Nullable<System.DateTime> RIMEDT { get; set; }
        public Nullable<bool> RIMFLG { get; set; }
        public string RIMORD { get; set; }
        public Nullable<int> RIMLIN { get; set; }
        public string RIMADE { get; set; }
        public string RIMBAR { get; set; }
        public string STATUS { get; set; }
    }
}
