//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVUOMP0
    {
        public string UOMDES { get; set; }
        public string UOMDEL { get; set; }
        public Nullable<System.DateTime> UOMDAT { get; set; }
        public string UOMUSR { get; set; }
        public string STATUS { get; set; }
    }
}
