//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVVEMP0
    {
        public int VEMVEN { get; set; }
        public Nullable<int> VEMWSI { get; set; }
        public string VEMDS1 { get; set; }
        public string VEMDS2 { get; set; }
        public string VEMCCD { get; set; }
        public string VEMZIP { get; set; }
        public string VEMCTY { get; set; }
        public string VEMSTR { get; set; }
        public string VEMTEL { get; set; }
        public string VEMSTN { get; set; }
        public string VEMLOC { get; set; }
        public Nullable<double> VEMDAY { get; set; }
        public string VEMTID { get; set; }
        public string VEMSTA { get; set; }
        public Nullable<System.DateTime> VEMDAT { get; set; }
        public string VEMUSR { get; set; }
        public string VEMADE { get; set; }
        public string VEMDEL { get; set; }
        public string STATUS { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Store { get; set; }
        public string Except_Store { get; set; }
    }
}
