//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITMGRP
    {
        public int Id { get; set; }
        public int Group_Id { get; set; }
        public string Group_Name { get; set; }
        public int Item_Code { get; set; }
        public string Item_Name { get; set; }
        public int Item_Type { get; set; }
        public int Group_Type { get; set; }
    }
}
