//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIM_Price
    {
        public string Id { get; set; }
        public Nullable<int> MIMMIC { get; set; }
        public string MIMNAM { get; set; }
        public Nullable<int> MITIER { get; set; }
        public Nullable<double> MIMOLP { get; set; }
        public Nullable<double> MIMNEP { get; set; }
    }
}
