//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIM_Price
    {
        public string Id { get; set; }
        public Nullable<int> MIMMIC { get; set; }
        public string MIMNAM { get; set; }
        public string MITIER { get; set; }
        public Nullable<double> MIMPRI { get; set; }
        public Nullable<double> MIMPRO { get; set; }
        public Nullable<double> MIMPRG { get; set; }
        public Nullable<double> MIMNPA { get; set; }
        public Nullable<double> MIMNPI { get; set; }
        public Nullable<double> MIMNPO { get; set; }
        public Nullable<double> MIMNPD { get; set; }
        public Nullable<double> MIMNNP { get; set; }
        public Nullable<System.DateTime> MIMPND { get; set; }
    }
}
