//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Tier
    {
        public int Id { get; set; }
        public string Dessers_Price_Tier { get; set; }
        public string Breakfast_Price_Tier { get; set; }
        public string Regular_Price_Tier { get; set; }
        public string McCafe_Level_2_Price_Tier { get; set; }
        public string McCafe_Level_3_Price_Tier { get; set; }
        public string McCafe_Bistro_Price_Tier { get; set; }
        public string MDS_Price_Tier { get; set; }
        public string Project_Gold_Price_Tier { get; set; }
    }
}
