//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIM_VEM_Lookup
    {
        public string RIM_VEM_ID { get; set; }
        public Nullable<int> RIMRIC { get; set; }
        public Nullable<int> VEMVEN { get; set; }
        public Nullable<double> RIMCPR { get; set; }
        public Nullable<double> PPERUN { get; set; }
        public Nullable<double> SCMCOD { get; set; }
<<<<<<< HEAD
=======
    
        public virtual INVRIMP0 INVRIMP0 { get; set; }
        public virtual INVVEMP0 INVVEMP0 { get; set; }
>>>>>>> 6dc5ebba081e3bc811a0f4a80a4611c1e8cf37bd
    }
}
