//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store_Profile()
        {
            this.STORE_MIMMIC_Lookup = new HashSet<STORE_MIMMIC_Lookup>();
        }
    
        public int STORE_NO { get; set; }
        public string STORE_NAME { get; set; }
        public string OWNERSHIP { get; set; }
        public string BREAKFAST_PRICE_TIER { get; set; }
        public string REGULAR_PRICE_TIER { get; set; }
        public string DC_PRICE_TIER { get; set; }
        public string MDS_PRICE_TIER { get; set; }
        public string MCCAFE_LEVEL_2_PRICE_TIER { get; set; }
        public string MCCAFE_LEVEL_3_PRICE_TIER { get; set; }
        public string MCCAFE_BISTRO_PRICE_TIER { get; set; }
        public string PROJECT_GOLD_PRICE_TIER { get; set; }
        public string BET { get; set; }
        public Nullable<int> PROFIT_CENTER { get; set; }
        public string REGION { get; set; }
        public string PROVINCE { get; set; }
        public string LOCATION { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string FRESH_OR_FROZEN { get; set; }
        public string PAPER_OR_PLASTIC { get; set; }
        public string SOFT_SERVE_OR_VANILLA_POWDER_MIX { get; set; }
        public string SIMPLOT_OR_MCCAIN { get; set; }
        public string MCCORMICK_OR_GSF { get; set; }
        public string STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_MIMMIC_Lookup> STORE_MIMMIC_Lookup { get; set; }
    }
}
