//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_MIMMIC_Lookup
    {
        public string STORE_MIMMIC_Id { get; set; }
        public Nullable<int> STORE_NO { get; set; }
        public Nullable<int> MIMMIC { get; set; }
    }
}
