//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Profile
    {
        public int STORE_NO { get; set; }
        public string STORE_NAME { get; set; }
        public Nullable<int> OWNERSHIP { get; set; }
        public Nullable<int> BREAKFAST_PRICE_TIER { get; set; }
        public Nullable<int> REGULAR_PRICE_TIER { get; set; }
        public Nullable<int> DC_PRICE_TIER { get; set; }
        public Nullable<int> MDS_PRICE_TIER { get; set; }
        public Nullable<int> MCCAFE_LEVEL_2_PRICE_TIER { get; set; }
        public Nullable<int> MCCAFE_LEVEL_3_PRICE_TIER { get; set; }
        public Nullable<int> MCCAFE_BISTRO_PRICE_TIER { get; set; }
        public Nullable<int> PROJECT_GOLD_PRICE_TIER { get; set; }
        public string BET { get; set; }
        public Nullable<int> PROFIT_CENTER { get; set; }
        public string REGION { get; set; }
        public string PROVINCE { get; set; }
        public Nullable<int> LOCATION { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string FRESH_OR_FROZEN { get; set; }
        public string PAPER_OR_PLASTIC { get; set; }
        public string SOFT_SERVE_OR_VANILLA_POWDER_MIX { get; set; }
        public string SIMPLOT_OR_MCCAIN { get; set; }
        public string MCCORMICK_OR_GSF { get; set; }
        public string FRESHB_OR_FROZENB { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> Group { get; set; }
    
        public virtual Breakfast_Price_Tier Breakfast_Price_Tier1 { get; set; }
        public virtual Dessert_Price_Tier Dessert_Price_Tier { get; set; }
        public virtual LOCATION LOCATION1 { get; set; }
        public virtual McCafe_Bistro_Price_Tier McCafe_Bistro_Price_Tier1 { get; set; }
        public virtual McCafe_Level_2_Price_Tier McCafe_Level_2_Price_Tier1 { get; set; }
        public virtual McCafe_Level_3_Price_Tier McCafe_Level_3_Price_Tier1 { get; set; }
        public virtual MDS_Price_Tier MDS_Price_Tier1 { get; set; }
        public virtual OWNERSHIP OWNERSHIP1 { get; set; }
        public virtual Project_Gold_Price_Tier Project_Gold_Price_Tier1 { get; set; }
        public virtual Regular_Price_Tier Regular_Price_Tier1 { get; set; }
    }
}
