//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMMCD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tier_Lookup
    {
        public int MIMMIC { get; set; }
        public Nullable<double> OLDPRA { get; set; }
        public Nullable<double> NEWPRA { get; set; }
        public Nullable<double> OLDPRB { get; set; }
        public Nullable<double> NEWPRB { get; set; }
        public Nullable<double> OLDPRC { get; set; }
        public Nullable<double> NEWPRC { get; set; }
        public Nullable<double> OLDPRD { get; set; }
        public Nullable<double> NEWPRD { get; set; }
        public Nullable<double> OLDPRE { get; set; }
        public Nullable<double> NEWPRE { get; set; }
        public Nullable<double> OLDPRF { get; set; }
        public Nullable<double> NEWPRF { get; set; }
        public Nullable<double> OLDMDS { get; set; }
        public Nullable<double> NEWMDS { get; set; }
        public Nullable<double> OLDPRS { get; set; }
        public Nullable<double> NEWPRS { get; set; }
    }
}
